In [12]:
# Module 3
# Checking for missing values

import pandas as pd
import numpy as np

df = pd.DataFrame({"Age": [12,14,np.nan,42],
                   "Marks": [12,np.nan,45,np.nan]}
                   )
print(df)
print()
# isnull()
print(df.isnull()) # return True in case of Null Values
print()
# Print count of columns which are null
print(df.isnull().sum())
print()
# Print the count of rows which are empty
print(df.isnull().sum(axis=1))
print()
# print the count of empty cells
print(df.isnull().sum().sum())
print()
# Find the percentage of empty cells in a column
print(df.isnull().sum()/len(df)*100)

    Age  Marks
0  12.0   12.0
1  14.0    NaN
2   NaN   45.0
3  42.0    NaN

     Age  Marks
0  False  False
1  False   True
2   True  False
3  False   True

Age      1
Marks    2
dtype: int64

0    0
1    1
2    1
3    1
dtype: int64

3

Age      25.0
Marks    50.0
dtype: float64

In [13]:
# Handling missing values
# 1) dropna - drop rows with missing values

import pandas as pd
import numpy as np

df = pd.DataFrame({"Name":["Alice","Bob",None,"Delta"],
                   "Age" : [13,np.nan,12,14]})
df = df.dropna()
print(df)

    Name   Age
0  Alice  13.0
3  Delta  14.0

In [ ]:
# 2) fillna - fills the missing values with a value
import pandas as pd
import numpy as np

df = pd.DataFrame({"Name":["Alice","Bob",None,"Delta"],
                   "Age" : [13,np.nan,12,14]})
print("Filling missing values with 0")
df = df.fillna(0)
print(df)
print()

Filling missing values with 0

In [21]:
print("Filling missing values with mean")
df["Age"]= df["Age"].fillna(df["Age"].mean())
print(df)

Filling missing values with mean
    Name   Age
0  Alice  13.0
1    Bob  13.0
2    NaN  12.0
3  Delta  14.0

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([10,20,np.nan,45,60]) # (20+45)/2 = 32.5 
s = s.fillna(s.median())
print(s)

0    10.0
1    20.0
2    32.5
3    45.0
4    60.0
dtype: float64

In [24]:
import pandas as pd
import numpy as np

s = pd.Series([10,20,20,np.nan])
s = s.fillna(s.mode()[0])
print(s)

0    10.0
1    20.0
2    20.0
3    20.0
dtype: float64

In [25]:
# 3) Replacing few values with nan
import pandas as pd
import numpy as np

df = pd.read_csv("Sales.csv",na_values=[-1,"None","NA"])
df.replace([-1,"NA"],np.nan)
df.head(2)

    Name   Age   Sal
0  Alice   NaN   NaN
1    NaN  18.0  78.0

In [26]:
# 4) Interpolation - guesses the missing values based on the values around it
import pandas as pd
import numpy as np

s = pd.Series([1,np.nan,3,4,5])
s = s.interpolate()
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [14]:
# Cleaning up csv file using converters
import pandas as pd
import numpy as np

def clean_price(val):
    try:
        return float(str(val).replace("$","").replace(",","").strip())
    except ValueError:
        return None

def clean_name(name):
    return str(name).strip().title()

df = pd.read_csv("Sales1.csv",
                 converters={"Price": clean_price,"Name": clean_name})

print(df)

    Name   Price
0  Alice  1000.0
1    Bob   400.0

In [31]:
# Cleaning up using students data

import pandas as pd
import numpy as np

df = pd.DataFrame({"Name":["Alice","NA","Bob","Charlie"],
                   "Age":[14,-1,23,45],
                   "Marks":[23,45,-1,89]})
df.to_csv("Students_details.csv",index=False)

df_read = pd.read_csv("Students_details.csv",na_values=[-1,"NA"])
print(df_read)
print()
df_read["Age"] = df_read["Age"].fillna("-")
df_read["Marks"] = df_read["Marks"].fillna(df_read["Marks"].median())
df_read["Name"] = df_read["Name"].fillna("Unknown")
print(df_read)
print()
print(f"Average marks : {df_read["Marks"].mean()}")
print(f"Top scorer is {df_read.loc[df_read["Marks"].idxmax(),"Name"]}")
print()
print(df_read.describe())

      Name   Age  Marks
0    Alice  14.0   23.0
1      NaN   NaN   45.0
2      Bob  23.0    NaN
3  Charlie  45.0   89.0

      Name   Age  Marks
0    Alice  14.0   23.0
1  Unknown     -   45.0
2      Bob  23.0   45.0
3  Charlie  45.0   89.0

Average marks : 50.5
Top scorer is Charlie

           Marks
count   4.000000
mean   50.500000
std    27.682726
min    23.000000
25%    39.500000
50%    45.000000
75%    56.000000
max    89.000000

In [44]:
# Cleanup in csv
import pandas as pd

df = pd.read_csv("Sales2.csv",na_values=["NA",-1])
# Inspect the values
df.head()
# Clean up column name
df.columns = df.columns.str.title()
print(df)
print()
# Clean up values
df["Name"]=df["Name"].str.title() # whenver you are using title() use str before that
df["Price"]=pd.to_numeric(df["Price"],errors = "coerce")
df["Date"]=pd.to_datetime(df["Date"],errors="coerce")
print(df)
# drop invalid rows
df = df.dropna()
print()
# reset index
df.reset_index(drop=True,inplace=True)
print(df)

    Name        Date  Price
0  alICE  2026-04-05   56.0
1    boB  2026-06-08   45.0
2    NaN         NaN    NaN

    Name       Date  Price
0  Alice 2026-04-05   56.0
1    Bob 2026-06-08   45.0
2    NaN        NaT    NaN

    Name       Date  Price
0  Alice 2026-04-05   56.0
1    Bob 2026-06-08   45.0

In [50]:
'''Types of joins
 1) Outer join - Join all columns in A and B
 2) Inner join - Join matching columns in A and B
 3) Left join - Join all columns in A and matching columns in B 
 use pd.merge() for all '''

import pandas as pd

employees = pd.DataFrame({"Name":["Alice","Bob","Charlie","Delta"],
                  "DeptID":[10,20,30,10],})
department = pd.DataFrame({"DeptID":[10,20],
                  "DeptName":["HR","Finance"]})

# Outer join
outer_join = pd.merge(employees,department,on="DeptID",how="outer")
print(outer_join)
print()
#inner join
inner_join = pd.merge(employees,department,on="DeptID",how="inner")
print(inner_join)
print()
# Left join
left_join = pd.merge(employees,department,on="DeptID",how="left")
print(left_join)
print()
# Right join
right_join = pd.merge(employees,department,on="DeptID",how="right")
print(right_join)

      Name  DeptID DeptName
0    Alice      10       HR
1    Delta      10       HR
2      Bob      20  Finance
3  Charlie      30      NaN

    Name  DeptID DeptName
0  Alice      10       HR
1    Bob      20  Finance
2  Delta      10       HR

      Name  DeptID DeptName
0    Alice      10       HR
1      Bob      20  Finance
2  Charlie      30      NaN
3    Delta      10       HR

    Name  DeptID DeptName
0  Alice      10       HR
1  Delta      10       HR
2    Bob      20  Finance

In [51]:
# JSON - JavaScript Object Notation
# 1)reading from a json string

import pandas as pd
from io import StringIO

json_str = '''
           [
           {"Name":"Alice","Age": 18},
           {"Name":"Bob","Age":23}] 
'''
df = pd.read_json(StringIO(json_str))
print(df)

    Name  Age
0  Alice   18
1    Bob   23

In [52]:
# 2) Reading from json file
import pandas as pd
df = pd.read_json("1.json")
print(df)

    Name  Age
0  Alice   18
1    Bob   20

In [58]:
# 3) Reading from complex json file
import json
import pandas as pd

with open("complex_json.json","r") as f:
    data = json.load(f)

row = data["employees"]
df = pd.DataFrame(row)
print(df)

   id   Name  Age
0   1  Alice   13
1   2    Bob   20

In [62]:
# 4) Normalization of json 
import pandas as pd


data =  [
            {
                "Name":"Alice","Age":18,
                "Address":{"City":"Bengaluru","Pincode":560023}
            },
            {
                "Name":"Bob","Age":20,
                "Address":{"City":"Chennai","Pincode":600023}
            }
        ]
    
            
df = pd.json_normalize(data)
print(df)

    Name  Age Address.City  Address.Pincode
0  Alice   18    Bengaluru           560023
1    Bob   20      Chennai           600023

In [67]:
# Write a dataframe to a json file
import pandas as pd

df = pd.DataFrame({"Name":["Alice","Bob","Charlie"],
                   "Age":[23,24,25]
                   })
df.to_json("Info.json",orient ="records",indent=2)

In [5]:
# -- HTML--
# 1) read from a html page
import pandas as pd

table = pd.read_html("https://www.w3schools.com/html/html_tables.asp",match="Country")
print(f"Number of tables :{len(table)}")
print(table[0])

Number of tables :1
                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [12]:
# XML file
# Reading from a XML file
import pandas as pd
df = pd.read_xml("students.xml")
print(df)

# Writing to a xml file
df = pd.DataFrame({"Name":["Alice"],"Age":[20]})
df.to_xml("Alice.xml",root_name="Alice",row_name="Student",index=False)

    Name  Marks
0  Alice     20

In [ ]:
# -- ANALYSIS --
# 1) SORTING
# SYNTAX : df.sort_values(column_name)
import pandas as pd

df = pd.DataFrame({"Name":["Alice","Bob","Charlie","Delta"],
                   "Dept":["HR","Finance","IT","HR"],
                   "Salary": [10,45,100,90]})

print(df.sort_values("Salary"))
print()
print(df.sort_values("Salary",ascending= False))
print()
print(df.sort_values(["Dept","Salary"],ascending=[True,False]))
print()
# 2) Filtering
print(df[df["Salary"]>50])
print()
print(df[
        (df["Salary"]>90)
        &
        (df["Dept"]=="IT")
    ])
print()
print(
    df[
        (df["Dept"]=="Finance") | (df["Dept"]=="IT")
    ]
)

      Name     Dept  Salary
0    Alice       HR      10
1      Bob  Finance      45
3    Delta       HR      90
2  Charlie       IT     100

      Name     Dept  Salary
2  Charlie       IT     100
3    Delta       HR      90
1      Bob  Finance      45
0    Alice       HR      10

      Name     Dept  Salary
1      Bob  Finance      45
3    Delta       HR      90
0    Alice       HR      10
2  Charlie       IT     100

      Name Dept  Salary
2  Charlie   IT     100
3    Delta   HR      90

      Name Dept  Salary
2  Charlie   IT     100

      Name     Dept  Salary
1      Bob  Finance      45
2  Charlie       IT     100

In [16]:
# 3) Applying functions
df["Bonus"] = df["Salary"].apply(lambda x : x *0.1)
print(df)
print()
df["New_Bonus"] = df.apply(
    lambda rows : rows["Salary"]*0.5
                if rows["Dept"]=="IT"
                else rows["Salary"]*0.2,
                axis =1)
print(df)

      Name     Dept  Salary  Bonus
0    Alice       HR      10    1.0
1      Bob  Finance      45    4.5
2  Charlie       IT     100   10.0
3    Delta       HR      90    9.0

      Name     Dept  Salary  Bonus  New_Bonus
0    Alice       HR      10    1.0        2.0
1      Bob  Finance      45    4.5        9.0
2  Charlie       IT     100   10.0       50.0
3    Delta       HR      90    9.0       18.0

In [20]:
# Pivot - It is used to summarize a large table using aggregate functions
pd.pivot_table(
    df,
    values = "Salary",
    index = "Name",
    columns = "Dept",
    aggfunc="sum",
    fill_value = 0
)

Dept     Finance  HR   IT
Name
Alice          0  10    0
Bob           45   0    0
Charlie        0   0  100
Delta          0  90    0

In [10]:
# groupby - split , apply,combine
# syntax : df.groupby(group_column)[value_column].func()
import pandas as pd
df = pd.DataFrame({"Name":["Alice","Bob","Charlie","Diana","Eve"],
                   "Dept":["IT","Finance","IT","HR","Sales"],
                   "Grade":["Junior","Senior","Senior","Junior","Senior"],
                   "Salary":[100,122,123,124,67]})
print(df.groupby("Dept")["Salary"].mean())
print()
print(df.groupby("Dept")["Salary"].max())
print()
print(df.groupby("Dept")["Salary"].min())
print()
print(df.groupby("Dept")["Salary"].count())
# Add multiple agg functions together
print()
print(df.groupby("Dept")["Salary"].agg(["mean","max","min","count"]))
# group mutiple columns
result = df.groupby(["Dept","Grade"])["Salary"].mean()
print(result)

Dept
Finance    122.0
HR         124.0
IT         111.5
Sales       67.0
Name: Salary, dtype: float64

Dept
Finance    122
HR         124
IT         123
Sales       67
Name: Salary, dtype: int64

Dept
Finance    122
HR         124
IT         100
Sales       67
Name: Salary, dtype: int64

Dept
Finance    1
HR         1
IT         2
Sales      1
Name: Salary, dtype: int64

          mean  max  min  count
Dept
Finance  122.0  122  122      1
HR       124.0  124  124      1
IT       111.5  123  100      2
Sales     67.0   67   67      1
Dept     Grade
Finance  Senior    122.0
HR       Junior    124.0
IT       Junior    100.0
         Senior    123.0
Sales    Senior     67.0
Name: Salary, dtype: float64